server.port=${PORT:8080}

# MongoDB Atlas (Cloud Database)
spring.mongodb.uri=mongodb+srv://admin:admin@cluster0.kfihdgy.mongodb.net/timecapsule?retryWrites=true&w=majority
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${kavyaananya152710@gmail.com}
spring.mail.password=${sdjn iiat ohom dnih}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

scheduler.fixed-rate=60000